# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'info.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_infoForm(object):
    def setupUi(self, infoForm):
        infoForm.setObjectName("infoForm")
        infoForm.resize(380, 120)
        infoForm.setMinimumSize(QtCore.QSize(380, 120))
        infoForm.setMaximumSize(QtCore.QSize(380, 120))
        self.textBrowser = QtWidgets.QTextBrowser(infoForm)
        self.textBrowser.setEnabled(True)
        self.textBrowser.setGeometry(QtCore.QRect(10, 10, 360, 100))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textBrowser.sizePolicy().hasHeightForWidth())
        self.textBrowser.setSizePolicy(sizePolicy)
        self.textBrowser.setMinimumSize(QtCore.QSize(0, 0))
        self.textBrowser.setMaximumSize(QtCore.QSize(360, 100))
        self.textBrowser.setObjectName("textBrowser")

        self.retranslateUi(infoForm)
        QtCore.QMetaObject.connectSlotsByName(infoForm)

    def retranslateUi(self, infoForm):
        _translate = QtCore.QCoreApplication.translate
        infoForm.setWindowTitle(_translate("infoForm", "Info"))
        self.textBrowser.setHtml(_translate("infoForm", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">Основные правила.</span><br />Ваша цель активировать все доступные ячейки игрового поля, при активации ячеек вам необходимо учитывать:<br /><span style=\" font-weight:600;\">1)</span>следующая ячейка должна быть того же цвета или той же формы как предыдущая ячейка</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">2)</span>вы можете ходить только по горизонтали или вертикали</p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    infoForm = QtWidgets.QWidget()
    ui = Ui_infoForm()
    ui.setupUi(infoForm)
    infoForm.show()
    sys.exit(app.exec_())
